image: python:3.8

variables:
  IMAGE_VERSION: 1.0.0
  WORK_DIR: .
  NODE_ENV: development
  DOCKER_DRIVER: overlay2
  DOCKER_FILE: Dockerfile
  DOCKER_IMAGE: ${IMAGE_VERSION}
  DOCKER_BUILD_CONTEXT: .
cache:
  key: ${CI_COMMIT_REF_SLUG}
stages:
  - deploy
Deploy:
  stage: deploy
  only:
    - deploy
  tags:
    - fullstack_api
  script:
    - docker stop $(docker ps -aq) || true
    - docker build -t ${DOCKER_IMAGE}
    - docker run -it -d -p 8080:80 --restart=unless-stopped ${DOCKER_IMAGE}
    